### ISSUE TITLE
Add instructions for adding content to Jupyter Book

### ISSUE THREAD

**Issue by s-a-s-h** [openteamsinc/engineering-team-resource-book#1]
Central Jupyter Book, containing documentation spanning multiple projects.
- [x] Intro page with description
- [x] Create instructions for other team members to add content 
- [x] Have consistent formatting, explain formatting in instructions
- [ ] Add developer guidelines

**add template to this repository

**Comment by ftarlaci** [comment]
@s-a-s-h What do you think about adding our developer guidelines to this jupyter book as a first chapter?   This is the pdf version: https://drive.google.com/file/d/1PXn1Twq30JszKdR6HBberZosNHn8dVOU/view but the word version is in the engineering folder in google drive as well ( the latest version that the team reviewed before we finalized it.)

**Comment by s-a-s-h** [comment]
That's a good idea, I will add to the description.

**Comment by s-a-s-h** [comment]
I am making a new small issue to add the developer guidelines, for new sprint board. This issue will be linked.
